services:
  - type: web
    name: nexus-board-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        sync: false

  - type: web
    name: nexus-board-ui
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FASTAPI_URL
        sync: false